//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sks_toolkit.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sks_toolkit.Resources.Languages.zh-CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 这是你第一次使用吗? 的本地化字符串。
        /// </summary>
        internal static string SetLanguage_FirstGreeting {
            get {
                return ResourceManager.GetString("SetLanguage_FirstGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击下面的下一步按钮，即刻开始体验~ 的本地化字符串。
        /// </summary>
        internal static string SetLanguage_HowToStart {
            get {
                return ResourceManager.GetString("SetLanguage_HowToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是正确的语言吗? 的本地化字符串。
        /// </summary>
        internal static string SetLanguage_IsRightLanguage {
            get {
                return ResourceManager.GetString("SetLanguage_IsRightLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只用花几分钟完成设置。 的本地化字符串。
        /// </summary>
        internal static string SetLanguage_ToStartSet {
            get {
                return ResourceManager.GetString("SetLanguage_ToStartSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一步 的本地化字符串。
        /// </summary>
        internal static string WelcomePage_Back {
            get {
                return ResourceManager.GetString("WelcomePage_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string WelcomePage_Finish {
            get {
                return ResourceManager.GetString("WelcomePage_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎来到 的本地化字符串。
        /// </summary>
        internal static string WelcomePage_Header {
            get {
                return ResourceManager.GetString("WelcomePage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        internal static string WelcomePage_Next {
            get {
                return ResourceManager.GetString("WelcomePage_Next", resourceCulture);
            }
        }
    }
}
